language: java

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - ./travis-build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: bintray
  skip_cleanup: true
  file: target/bin/bintray.json
  user: $BINTRAY_API_USER
  key: $BINTRAY_API_KEY